name: ✨ 功能請求
description: 建議新功能或改進
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感謝你提出功能建議！請詳細描述你的想法。

  - type: checkboxes
    id: checklist
    attributes:
      label: 確認清單
      options:
        - label: 我已搜尋過現有的 issues 和 discussions
          required: true
        - label: 這個功能與 YOLO 物件偵測專案相關
          required: true

  - type: dropdown
    id: category
    attributes:
      label: 功能類別
      options:
        - 資料處理
        - 模型訓練
        - API 功能
        - 前端介面
        - Claude Code Commands
        - Claude Code Plugins
        - Claude Code Hooks
        - 文檔改進
        - 部署相關
        - 其他
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 問題或需求
      description: 描述你想要解決的問題或需求
      placeholder: 例如：目前無法批次處理多個圖片，需要一張一張上傳很麻煩
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提議的解決方案
      description: 描述你希望如何實現這個功能
      placeholder: |
        建議新增批次上傳功能：
        1. 允許選擇多個圖片檔案
        2. 後端提供 /predict/batch 端點
        3. 回傳所有圖片的偵測結果
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 是否有考慮過其他實現方式？
      placeholder: |
        替代方案 1：使用 ZIP 檔案上傳
        替代方案 2：提供資料夾路徑

  - type: textarea
    id: use_cases
    attributes:
      label: 使用場景
      description: 這個功能會在什麼情況下使用？
      placeholder: |
        - 工廠品質檢測需要批次處理大量圖片
        - 影片幀提取後需要批次分析
        - 資料集驗證時需要快速檢視多張圖片的偵測結果

  - type: textarea
    id: benefits
    attributes:
      label: 預期效益
      description: 實現這個功能會帶來什麼好處？
      placeholder: |
        - 提升處理效率 10 倍
        - 減少重複操作
        - 改善使用者體驗

  - type: dropdown
    id: priority
    attributes:
      label: 優先級
      description: 你認為這個功能有多重要？
      options:
        - 低（Nice to have）
        - 中（Would be helpful）
        - 高（Really need this）
        - 關鍵（Blocking current work）
    validations:
      required: true

  - type: textarea
    id: mockup
    attributes:
      label: UI/UX 設計（如適用）
      description: 如果是前端功能，可以提供設計草圖或範例
      placeholder: |
        [可以貼上圖片或描述 UI]
        - 新增「批次上傳」按鈕在...位置
        - 顯示進度條
        - 結果以列表形式呈現

  - type: textarea
    id: technical
    attributes:
      label: 技術建議（選填）
      description: 如果你有技術實作的想法
      placeholder: |
        建議使用：
        - FastAPI 的 List[UploadFile] 處理多檔案
        - asyncio 並發處理提升速度
        - 前端使用 Promise.all 同時上傳

  - type: textarea
    id: examples
    attributes:
      label: 參考範例
      description: 有類似的實作可以參考嗎？
      placeholder: |
        - Roboflow 的批次推論功能
        - YOLOv5 官方的 batch prediction
        - https://example.com/similar-feature

  - type: checkboxes
    id: contribution
    attributes:
      label: 貢獻意願
      options:
        - label: 我願意協助實作這個功能
          required: false
        - label: 我可以協助撰寫文檔
          required: false
        - label: 我可以協助測試
          required: false

  - type: textarea
    id: additional
    attributes:
      label: 其他資訊
      description: 任何其他相關資訊
